### ISSUE TITLE
Time Zone?

### ISSUE THREAD

**Issue by dherl0623** [cowboysdude/MMM-NOAA#19]
I wondered if this module uses the time settings that are set in the Raspberry Pi? This module will show the moon several hours before the sun goes down and the sun will show several hours before it comes up. If I enable showing the time it is the same as my Magic Mirror time.  

Also, is there any way to load more than three days on the forecast? Using the Cumulus Plan API gives you access to the 10-day forecast. Maybe a future commit could have sch an option? 

This is the best weather module I have seen by the way! Thanks

**Comment by cowboysdude** [comment]
No it does not rely on the Pi time settings because it wasn't built to run on a Pi actually it was built to run on a desktop computer LOL.  It just simply relies on what wunderground is sending as data and uses the info it gets from that...so the time zone wouldn't really matter in this case :)

It originally showed 10 days but with limited space on most people's mirrors they requested it only show 3 [today plus the next 3 days] ... BUT if you'd like I could probably fix yours to show 10!  I will look at it later when I get home from work!

Thanks, we are glad you like it!  There were a few people building this so it was a labor of love, trust me.  It started out as something I made for just me but other saw it and wanted it soooooooo....that's how things get started.

**Comment by dherl0623** [comment]
Oh ok. Not a huge deal on the sun and moon icon thing. I was just curious! 

I see, I would love that if you don't mind! I think having the option would be awesome. I have been messing around with the javascript file, but I'm not well versed in javascript, and haven't quite gotten it yet. 

I just realized I also use your Xmas and History module too! Thanks again man!

**Comment by cowboysdude** [comment]
I'm looking at making it a config option to show 3 or 10 :)  I'm waiting
back on an answer from someone who issued a pull request to see if that's a
valid request or not.  I don't want to make changes then have a pull
request behind it as it may screw up my changes LOL

This history module has been VERY popular.... as is the RandomFacts one I
just recently did......people like me, like their info! hahahhah

Right now I'm off to work... I will talk to you soon!  Thank you!

**Comment by cowboysdude** [comment]
You can do a git pull and read the read me.......it will now show 10 days :) Basically just add this to the config days: "10",   👍
